# MOCK — replace with real DILRMP/Bhu-Naksha/ULPIN integration in production

MOCK_LAND_RECORDS = [
    {"ulpin": "ULPIN-MH-PUN-1001", "owner_name": "Ramesh Patil", "area_hectares": 2.5, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-PUN-1002", "owner_name": "Sunita Deshmukh", "area_hectares": 1.8, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-PUN-1003", "owner_name": "Ganesh Jadhav", "area_hectares": 3.2, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-PUN-1004", "owner_name": "Priya Kulkarni", "area_hectares": 0.9, "land_use": "RESIDENTIAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-PUN-1005", "owner_name": "Vijay Shinde", "area_hectares": 4.1, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-PUN-1006", "owner_name": "Aarti Bhosale", "area_hectares": 1.5, "land_use": "COMMERCIAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-PUN-1007", "owner_name": "Manoj Chavan", "area_hectares": 2.8, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-PUN-1008", "owner_name": "Rekha Gaikwad", "area_hectares": 1.2, "land_use": "BARREN", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-PUN-1009", "owner_name": "Suresh More", "area_hectares": 5.0, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-PUN-1010", "owner_name": "Kavita Pawar", "area_hectares": 2.0, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-NGP-2001", "owner_name": "Arun Wankhede", "area_hectares": 3.5, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-NGP-2002", "owner_name": "Meera Deshpande", "area_hectares": 1.1, "land_use": "RESIDENTIAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-NGP-2003", "owner_name": "Prakash Thakare", "area_hectares": 4.7, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-NGP-2004", "owner_name": "Lata Meshram", "area_hectares": 2.3, "land_use": "FOREST", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-MH-NGP-2005", "owner_name": "Rajendra Borkar", "area_hectares": 1.6, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-RJ-JPR-3001", "owner_name": "Lakshman Singh Rathore", "area_hectares": 6.2, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-RJ-JPR-3002", "owner_name": "Geeta Devi Sharma", "area_hectares": 3.0, "land_use": "BARREN", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-RJ-JPR-3003", "owner_name": "Bhagwan Das Meena", "area_hectares": 2.7, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-KA-BLR-4001", "owner_name": "Venkatesh Gowda", "area_hectares": 1.4, "land_use": "COMMERCIAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-KA-BLR-4002", "owner_name": "Shobha Reddy", "area_hectares": 3.8, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-KA-BLR-4003", "owner_name": "Ravi Kumar Hegde", "area_hectares": 2.1, "land_use": "RESIDENTIAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-TN-CHN-5001", "owner_name": "Murugan Selvam", "area_hectares": 4.5, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-TN-CHN-5002", "owner_name": "Lakshmi Narayanan", "area_hectares": 1.7, "land_use": "WETLAND", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-UP-LKO-6001", "owner_name": "Ram Prasad Yadav", "area_hectares": 5.3, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
    {"ulpin": "ULPIN-UP-LKO-6002", "owner_name": "Sita Devi Mishra", "area_hectares": 2.9, "land_use": "AGRICULTURAL", "source_system": "DILRMP-MOCK"},
]
